name: Half-year calendar

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Half-year calendar
        uses: Daniel-S-Allen/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_topics: yes
          plugin_topics_mode: labels
          base: header, activity, community, repositories, metadata
