name: Profile Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          base: ''
      - name: Topics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_topics: yes
          plugin_topics_mode: labels
          base: ''
      - name: Base
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
